CREATE TABLE IF NOT EXISTS app_user (
                                        id bigint generated by default as identity not null,
                                        email character varying(255) not null,
    first_name character varying(255) not null,
    last_name character varying(255) not null,
    password character varying(255) not null,
    role character varying(255) not null,
    constraint app_user_pkey primary key (id),
    constraint uk1j9d9a06i600gd43uu3km82jw unique (email),
    constraint app_user_role_check check (
    (
(role)::text = any (
    (
                       array[
                       'USER'::character varying,
                       'ADMIN'::character varying
    ]
                            )::text[]
    )
    )
    )
    );

CREATE TABLE IF NOT EXISTS product (
                                       id bigint generated by default as identity not null,
                                       description character varying(500) null,
    image_url character varying(255) null,
    name character varying(255) not null,
    price numeric(38, 2) null,
    slug character varying(255) not null,
    constraint product_pkey primary key (id),
    constraint uk88yb4l9100epddqsrdvxerhq9 unique (slug)
    );

CREATE TABLE IF NOT EXISTS drawing (
                                       id bigint generated by default as identity not null,
                                       description character varying(500) null,
    image_url character varying(255) not null,
    name character varying(255) not null,
    slug character varying(255) not null,
    constraint drawing_pkey primary key (id),
    constraint ukpjsq1t2kx0dqt1oqvb1ueap0k unique (slug)
    );

CREATE TABLE IF NOT EXISTS contact_message (
                                               id bigint generated by default as identity not null,
                                               budget character varying(255) null,
    company character varying(255) null,
    due_date character varying(255) null,
    email character varying(255) not null,
    full_name character varying(255) not null,
    message character varying(2000) not null,
    pronouns character varying(100) null,
    website_or_profile character varying(500) null,
    attachment_url character varying(500) null,
    constraint contact_message_pkey primary key (id)
    );

CREATE TABLE IF NOT EXISTS cart_item (
                                         id bigint generated by default as identity not null,
                                         quantity integer null,
                                         product_id bigint not null,
                                         guest_session_id character varying(255) null,
    user_id bigint null,
    created_at timestamp without time zone null,
    constraint cart_item_pkey primary key (id),
    constraint fkjcyd5wv4igqnw413rgxbfu4nv foreign key (product_id) references product (id),
    constraint fkn1boxy63txpdcfv6ahrw2wdui foreign key (user_id) references app_user (id)
    );

CREATE TABLE IF NOT EXISTS favourite_item (
                                              id bigint generated by default as identity not null,
                                              product_id bigint not null,
                                              user_id bigint not null,
                                              constraint favourite_item_pkey primary key (id),
    constraint fk25mhuj5cx19shgm4ajj0nl8u9 foreign key (user_id) references app_user (id),
    constraint fkl2sta31td3n1upominqdp9not foreign key (product_id) references product (id)
    );