CREATE TABLE IF NOT EXISTS orders (
                                      id bigint generated by default as identity not null,
                                      session_id character varying(255) null,
    customer_email character varying(255) null,
    customer_name character varying(255) null,
    address_line1 character varying(255) null,
    city character varying(255) null,
    postal_code character varying(255) null,
    country character varying(10) null,
    status character varying(20) not null,
    total_amount numeric(10, 2) not null,
    stripe_payment_intent_id character varying(255) not null,
    created_at timestamp without time zone null,
    constraint orders_pkey primary key (id),
    constraint uk_stripe_payment_intent_id unique (stripe_payment_intent_id)
    );

CREATE TABLE IF NOT EXISTS order_items (
                                           id bigint generated by default as identity not null,
                                           order_id bigint not null,
                                           product_id bigint not null,
                                           product_name character varying(255) not null,
    quantity integer not null,
    price_at_purchase numeric(10, 2) not null,
    constraint order_items_pkey primary key (id),
    constraint fk_order_items_order foreign key (order_id) references orders(id)
    );