name: Trigger auto deployment for fyt-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ main ]
    paths:
      - '**'
      - '.github/workflows/fyt-backend-AutoDeployTrigger-712a0d4b-1ba2-4038-8c89-27fede7c190c.yml'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FYTBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FYTBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FYTBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: fillyourtoteregistry-cvbsh0b6bwbhhefn.azurecr.io
          registryUsername: ${{ secrets.FYTBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FYTBACKEND_REGISTRY_PASSWORD }}
          containerAppName: fyt-backend
          resourceGroup: fillyourtote-resources
          imageToBuild: fillyourtoteregistry-cvbsh0b6bwbhhefn.azurecr.io/fyt-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_

